**Ejercicio 1:** Resolver los sistemas de ecuaciones lineales $Ax = b$ con la factorización P, LU y verificar resultado.

$$ A = \left[\begin{array}{ccc}
0 & 1& -1\\
-2 & 4& -1\\
-2 & 5& -4
\end{array}
\right],
b=
\left[\begin{array}{c}
3\\
1\\
-2
\end{array}
\right] 
$$

In [1]:
#Importando la paquetería necesaria para ejecutar la factorización P, LU.
import scipy
import scipy.linalg 
import numpy as np
import pprint


In [2]:
#Ingresando los valores de la matriz A:

A = scipy.array([[0,1,-1],[-2,4,-1],[-2,5,-4]])

#Obteniendo los factores P, L, U de la matriz A:
P, L, U = scipy.linalg.lu(A)

print('A:')
pprint.pprint(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)

A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])


In [3]:
#Verificando que LU es igual a PA.

print('Verificando que es igual LU al producto PA')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

Verificando que es igual LU al producto PA
L*U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])
P*A
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])


In [4]:
#Empleando los factores P, L, U para resolver AX=B

print('Usando los factores P,L,U para resolver AX = B')

B = scipy.array([[3],[1],[-2]])

D = scipy.linalg.solve_triangular(L,P@B,lower=True)
X = scipy.linalg.solve_triangular(U,D) #default es usar una triangular superior
print('X:')
pprint.pprint(X)

Usando los factores P,L,U para resolver AX = B
X:
array([[10.],
       [ 6.],
       [ 3.]])


In [5]:
#Verificando que AX=B
print('Verificando resultado AX = B')
print('B:')
pprint.pprint(B)
print('AX:')
pprint.pprint(A@X)

Verificando resultado AX = B
B:
array([[ 3],
       [ 1],
       [-2]])
AX:
array([[ 3.],
       [ 1.],
       [-2.]])


$$ A = \left[\begin{array}{ccc}
0 & 1& -1\\
-2 & 4& -1\\
-2 & 5& -4
\end{array}
\right],
b=
\left[\begin{array}{c}
-5\\
7\\
0
\end{array}
\right] 
$$

In [6]:
#Ingresando los valores de la matriz A:

A = scipy.array([[0,1,-1],[-2,4,-1],[-2,5,-4]])

#Obteniendo los factores P, L, U de la matriz A:
P, L, U = scipy.linalg.lu(A)

print('A:')
pprint.pprint(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)

#No es necesario verificar que LU es igual a PA, puesto que esto se realizó en el ejericicio previo. 

A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])


In [7]:
#Empleando los factores P, L, U para resolver AX=B

print('Usando los factores P,L,U para resolver AX = B')

B = scipy.array([[-5],[7],[0]])

D = scipy.linalg.solve_triangular(L,P@B,lower=True)
X = scipy.linalg.solve_triangular(U,D) #default es usar una triangular superior
print('X:')
pprint.pprint(X)

Usando los factores P,L,U para resolver AX = B
X:
array([[-12.],
       [ -4.],
       [  1.]])


In [8]:
print('Verificando resultado AX = B')
print('B:')
pprint.pprint(B)
print('AX:')
pprint.pprint(A@X)

Verificando resultado AX = B
B:
array([[-5],
       [ 7],
       [ 0]])
AX:
array([[-5.],
       [ 7.],
       [ 0.]])


$$ A = \left[\begin{array}{ccc}
1 & 2& 2\\
2 & 5& 7\\
3 & 6& 6
\end{array}
\right],
b=
\left[\begin{array}{c}
0\\
0\\
0
\end{array}
\right] 
$$

In [9]:
#Ingresando los valores de la matriz A:

A = scipy.array([[1,2,2],[2,5,7],[3,6,6]])

#Obteniendo los factores P, L, U de la matriz A:
P, L, U = scipy.linalg.lu(A)

print('A:')
pprint.pprint(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)

A:
array([[1, 2, 2],
       [2, 5, 7],
       [3, 6, 6]])
P:
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.        , 1.        ]])
U:
array([[3., 6., 6.],
       [0., 1., 3.],
       [0., 0., 0.]])


In [10]:
#Verificando que LU es igual a PA.

print('Verificando que es igual LU al producto PA')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

Verificando que es igual LU al producto PA
L*U:
array([[3., 6., 6.],
       [2., 5., 7.],
       [1., 2., 2.]])
P*A
array([[3., 6., 6.],
       [2., 5., 7.],
       [1., 2., 2.]])


In [11]:
#Empleando los factores P, L, U para resolver AX=B

print('Usando los factores P,L,U para resolver AX = B')

B = scipy.array([[0],[0],[0]])

D = scipy.linalg.solve_triangular(L,P@B,lower=True)
X = scipy.linalg.solve_triangular(U,D) #default es usar una triangular superior
print('X:')
pprint.pprint(X)

Usando los factores P,L,U para resolver AX = B


LinAlgError: singular matrix: resolution failed at diagonal 2

**Ejercicio 2:** Resolver el ejercicio con la factorización QR del paquete numpy de la matriz A y verificar resultado.

$$ A = \left[\begin{array}{ccc}
1 & 4& 1\\
1 & 6& -1\\
2 & -1& 2
\end{array}
\right],
b=
\left[\begin{array}{c}
7& -1\\
13& 6\\
5& 7
\end{array}
\right] 
$$

In [12]:
A = np.array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = np.array([[7, -1], [13, 6], [5, 7]])

In [13]:
#Calculando Q y R con el paquete numpy
q, r = np.linalg.qr(A)

In [14]:
print("qr factorization of the said array:")
print( "q=\n", q, "\nr=\n", r)

qr factorization of the said array:
q=
 [[-0.40824829 -0.40985242 -0.81569255]
 [-0.40824829 -0.71724173  0.56471022]
 [-0.81649658  0.56354707  0.12549116]] 
r=
 [[-2.44948974 -3.26598632 -1.63299316]
 [ 0.         -6.5064071   1.43448345]
 [ 0.          0.         -1.12942045]]


In [15]:
#Verificando el resultado: A=QR
q@r


array([[ 1.,  4.,  1.],
       [ 1.,  6., -1.],
       [ 2., -1.,  2.]])